resolver: lts-20.11

packages:
- . 

extra-deps:
- defun-core-0.1
- git: https://github.com/kztk-m/EbU.git
  commit: c483f604e81fe0aef66b0779ac13ea4774a476b7


allow-newer: true
allow-newer-deps: [defun-core]
